### ISSUE TITLE
Mouse Smoothing Bug

### ISSUE THREAD

**Issue by iCHOPPERi** [GTAmodding/FramerateVigilante#18]
The mouse seems to kinda delay and smooth out like reverse acceleration

Especially noticable with low sensitivity, happens on all GTA's

https://user-images.githubusercontent.com/22107981/175489725-fd6fb677-36c4-4da5-90d7-17c421e4dac4.mp4

**Comment by mirh** [comment]
This mod is about high framereate, not low sensibility. 

https://www.pcgamingwiki.com/wiki/Grand_Theft_Auto:_San_Andreas#RAW_input
This is probably more up to your task.

**Comment by iCHOPPERi** [comment]
I thought this happened with this mod specifically, but when I tried locking my fps in other ways, it still happened so it's not this mod's fault, also sorry for the late answer
