### ISSUE TITLE
Water plane cannot gain enough speed on water to start flying

### ISSUE THREAD

**Issue by Serlotus** [GTAmodding/FramerateVigilante#2]
Skimmer (water plane) id-460 cannot gain enough speed on water to start flying.

It tops out at around 25 KPH.

Testing settings: frame limiter on; FPS: 60.

**Comment by Serlotus** [comment]
Any reason?

**Comment by JuniorDjjr** [comment]
Was fixed, check new version.

https://github.com/GTAmodding/FramerateVigilante/commit/305fbcc555be86a48e6a1ca4c178020a529f18cf

**Comment by Serlotus** [comment]
Oh, I feel stupid now. Thanks 👍
