### ISSUE TITLE
[GTA SA]Under water speed

### ISSUE THREAD

**Issue by BlackShadow** [GTAmodding/FramerateVigilante#6]
When CJ dives to underwater his movement speed still effected by framerate.

**Comment by BlackShadow** [comment]
Closed, missed the line dive fix was added.

**Comment by BlackShadow** [comment]
Actually there's one issue with under water. CJ sinking in underwater. (Tested at 240FPS)

**Comment by ifarbod** [comment]
https://github.com/GTAmodding/FramerateVigilante/commit/9b8fc349b647d5c190d93ab4f606b163771953a6 fixes this
